

//game number:-
/*let gamenum=75;//(a%5==0);
let usernum=prompt("guess the game numb");
while(usernum!=gamenum){
    usernum=prompt("you entered wrong number.guess again:");
}
console.log("congratulation,you entered th right number");*/


//P.2
/*let userName=prompt("enter your full name ");
let username="@"+userName;//+userName.length;
let hel=userName.length;
let output=username+hel;
console.log(output);*/

//table..
/*let num=19;
for(i=1;i<=10;i++){
    multiple=num*i;
    console.log("19\t*",i,"=",multiple);
   // console.log("hello"+i);
}*/
